const $=id=>document.getElementById(id);
const audio=$("audio"), input=$("file-input"), tracksEl=$("tracks"), search=$("search");
let tracks=JSON.parse(localStorage.getItem("sbd-tracks")||"[]").map(t=>({...t,file:null}));
let current=-1, objectUrl=null, playlist=JSON.parse(localStorage.getItem("sbd-playlists")||"[]");
const fmt=s=>{if(!Number.isFinite(s))return"0:00";return`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,"0")}`};
function save(){localStorage.setItem("sbd-tracks",JSON.stringify(tracks.map(({file,...t})=>t)));localStorage.setItem("sbd-playlists",JSON.stringify(playlist))}
function render(){const q=search.value.toLowerCase();const shown=tracks.filter(t=>t.title.toLowerCase().includes(q));$("count").textContent=`${shown.length} položek`;tracksEl.innerHTML=shown.length?shown.map(t=>`<div class="track"><button data-play="${t.id}">▶</button><div><strong>${t.title}</strong><small>${t.source||"Lokální soubor"} · ${t.type||"audio"}</small></div><time>${fmt(t.duration)}</time></div>`).join(""):`<div class="empty">Knihovna je prázdná.<br>Přidej audio soubory tlačítkem výše.</div>`;renderPlaylists()}
function renderPlaylists(){ $("playlist-list").innerHTML=playlist.length?playlist.map(p=>`<div class="playlist"><strong>${p.name}</strong><span>${p.ids.length} skladeb</span></div>`).join(""):`<div class="empty">Zatím nemáš žádný playlist.</div>`}
function select(t){current=tracks.indexOf(t);if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=t.file?URL.createObjectURL(t.file):"";audio.src=objectUrl;audio.currentTime=Number(localStorage.getItem(`sbd-pos-${t.id}`)||0);$("now-title").textContent=t.title;$("now-source").textContent=t.source||"Lokální soubor";$("art").textContent=t.title.slice(0,1).toUpperCase();audio.play().catch(()=>{});$("play").textContent="Ⅱ"}
input.addEventListener("change",e=>{[...e.target.files].forEach(file=>{const t={id:crypto.randomUUID(),title:file.name.replace(/\.[^.]+$/,""),type:file.type||"audio",source:"Lokální soubor",duration:0,file};tracks.push(t);const probe=new Audio(URL.createObjectURL(file));probe.addEventListener("loadedmetadata",()=>{t.duration=probe.duration;save();render()})});save();render();input.value=""});
tracksEl.addEventListener("click",e=>{const id=e.target.dataset.play;if(id)select(tracks.find(t=>t.id===id))});search.addEventListener("input",render);
$("play").onclick=()=>{if(current<0&&tracks[0])select(tracks[0]);else if(audio.paused){audio.play();$("play").textContent="Ⅱ"}else{audio.pause();$("play").textContent="▶"}};
$("next").onclick=()=>{if(tracks.length)select(tracks[(current+1)%tracks.length])};$("prev").onclick=()=>{if(tracks.length)select(tracks[(current-1+tracks.length)%tracks.length])};
audio.ontimeupdate=()=>{$("elapsed").textContent=fmt(audio.currentTime);$("duration").textContent=fmt(audio.duration);$("seek").max=audio.duration||100;$("seek").value=audio.currentTime; if(current>=0)localStorage.setItem(`sbd-pos-${tracks[current].id}`,audio.currentTime)};
$("seek").oninput=e=>{audio.currentTime=Number(e.target.value)};audio.onended=()=>$("next").click();
$("new-playlist").onclick=()=>{const name=prompt("Název playlistu");if(name?.trim()){playlist.push({name:name.trim(),ids:[]});save();render()}};
$("sleep").onchange=e=>{const minutes=Number(e.target.value);localStorage.setItem("sbd-sleep",minutes?String(Date.now()+minutes*60000):"0")};const sleep=Number(localStorage.getItem("sbd-sleep"));if(sleep>Date.now())$("sleep").value=String(Math.round((sleep-Date.now())/60000));setInterval(()=>{if(Number(localStorage.getItem("sbd-sleep"))<=Date.now()&&audio&&!audio.paused){audio.pause();$("play").textContent="▶";localStorage.setItem("sbd-sleep","0");$("sleep").value="0"}},1000);
document.querySelectorAll(".tab").forEach(tab=>tab.onclick=()=>{document.querySelectorAll(".tab").forEach(t=>t.classList.remove("active"));tab.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.hidden=v.id!==tab.dataset.view)});
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");render();
